### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Barbery** [bergundy/libbeanstalkclient#2]
vagrant@precise64:/vagrant/php-beanstalk/libbeanstalkclient$ sudo ./autogen.sh 
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file`m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file`m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file`m4/lt~obsolete.m4'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
./configure: line 2806: syntax error near unexpected token `CHECK,'
./configure: line 2806:`   PKG_CHECK_MODULES(CHECK, check >= 0.9.4)'
make: **\* No targets specified and no makefile found.  Stop.
make: **\* No rule to make target `install'.  Stop.

**Comment by ryb** [comment]
This worked for me. I think you can merge it into master.
